### ISSUE TITLE
Windows Installer detected as Virus

### ISSUE THREAD

**Issue by AspireJames** [sorayuki/obs-multi-rtmp#102]
The windows setup package for this plugin is detected by various AV platforms as malware.

See here: https://www.hybrid-analysis.com/sample/6c6fe87c4ca631f3404e4ac1c0a62a5c736687b74127130633e087a581367c29 

https://www.virustotal.com/gui/file/6c6fe87c4ca631f3404e4ac1c0a62a5c736687b74127130633e087a581367c29/detection/f-6c6fe87c4ca631f3404e4ac1c0a62a5c736687b74127130633e087a581367c29-1625034147

**Comment by MagicPlants** [comment]
No answer to this?

**Comment by ileathan** [comment]
Looking at your post it appears the file is not a virus? 

Cloudstrike marks it as clean, meta defender marks it as 4% risk and the last is 15%?

Furthermore the details show its doing nothing more than it needs to, masquerading is probably used to use 1 stream and split it into the multiple outputs, software deletion is probably because it needs to delete older version if present before instalation, hooking credential probably to store the data.. Its all pretty self explanatory after that.

It can be hard to make programs that pass anti virus's, for example in my repo about 20 projects get marked as a virus because they run crypto miners on your pc at your bloody request. Anyway this project is open source and extremely small, i went through the code a bit and it seems fine.

**Comment by ileathan** [comment]
![image](https://user-images.githubusercontent.com/8704279/128579289-cc61816a-49ac-4afd-8af7-4fb274f0b148.png)

**Comment by ileathan** [comment]
Only the first few give false positives with details all extremely normal

https://www.virustotal.com/gui/file/6c6fe87c4ca631f3404e4ac1c0a62a5c736687b74127130633e087a581367c29/behavior

**Comment by lafinlalannges** [comment]
So is it safe or not?

**Comment by sorayuki** [comment]
The dll file and installer are built by github CI automatelly.
It should be not with virus.
