### ISSUE TITLE
add Linux bulid /为linux添加构建

### ISSUE THREAD

**Issue by logic10492** [sorayuki/obs-multi-rtmp#189]
i can see the shell script in source folder but i need to clone the source and run it for build this plugin
and because of the different Hierarchical structure of directory between linux and windows i need to change it after i build so that i can make obs cognition this plugin correctly

我看到在源码文件夹有为linux的构建脚本，但是我需要把源码下载下来并且编译，以及因为与windows不同的目录结构，生成的东西我还需要做一点额外修改才可以为obs正确识别

**Comment by sorayuki** [comment]
不会搞Linux…

**Comment by cincodenada** [comment]
I just got this plugin working under Linux with OBS v27, using the 0.2.7 branch (with [this fix](https://github.com/sorayuki/obs-multi-rtmp/pull/200) that is now merged), the only tricky part was figuring out the file structure. Here's what ended up working for me is the following file structure under `$HOME/.config/obs-studio/plugins`:
```
├── obs-multi-rtmp
│   ├── bin
│   │   └── 64bit
│   │       └── obs-multi-rtmp.so
│   ├── data
│   │   └── locale
│   │       ├── ca-ES.ini
│   │       ├── de-DE.ini
│   │       ├── en-US.ini
│   │       ├── es-ES.ini
│   │       ├── fr-FR.ini
│   │       ├── id-ID.ini
│   │       ├── ja-JP.ini
│   │       ├── ko-KR.ini
│   │       ├── nl-NL.ini
│   │       ├── pl-PL.ini
│   │       ├── pt-BR.ini
│   │       ├── pt-PT.ini
│   │       ├── ru-RU.ini
│   │       ├── sv-SE.ini
│   │       ├── tr-TR.ini
│   │       ├── uk-UA.ini
│   │       ├── vi-VN.ini
│   │       ├── zh-CN.ini
│   │       └── zh-TW.ini
```

So basically, create a `obs-multi-rtmp` folder under `$HOME/.config/obs-studio/plugins` and then
 - Files in `dist/usr/lib/obs-studio` go under `bin/64bit/`
 - Files in `dist/usr/share/obs-studio` go under `data/`

I don't know CMake super well but I may try updating the Linux build script so that the install part works too.
