### ISSUE TITLE
Dock forgets its position on restart

### ISSUE THREAD

**Issue by matoi974** [sorayuki/obs-multi-rtmp#41]
Steps to reproduce:
1. Enable both the obs-multi-rtmp dock and the Stats down in View > Docks.
![image](https://user-images.githubusercontent.com/63289008/89119308-d3c90080-d4c6-11ea-880d-0a45b75f907f.png)
2. Untick "Lock UI".
![image](https://user-images.githubusercontent.com/63289008/89119309-e3e0e000-d4c6-11ea-9975-8db6e527f06e.png)
3. Drag the "Multiple output" dock on top of the Stats dock so they're in tabs.
![image](https://user-images.githubusercontent.com/63289008/89119310-f824dd00-d4c6-11ea-81c4-3c9223af74bc.png)
4. Restart OBS. The dock will detach itself.
![image](https://user-images.githubusercontent.com/63289008/89119320-070b8f80-d4c7-11ea-9b31-165957d5bcbc.png)

**Comment by COOLIGUAY** [comment]
Same here.

In my case, at the start it always appears on the right side.
Windows 10.

**Comment by jat001** [comment]
that is because this plugin uses a custom config item `DockLocation` to save the dock location

this config item only saves the dock area, which is one of these numbers
```
1 Qt::DockWidgetArea::LeftDockWidgetArea
2 Qt::DockWidgetArea::RightDockWidgetArea
4 Qt::DockWidgetArea::TopDockWidgetArea
8 Qt::DockWidgetArea::BottomDockWidgetArea
0 Qt::DockWidgetArea::NoDockWidgetArea
```
other informations like dock size and dock position will not be saved

obs can save the dock state, but this plugin removed the dock and created a new one
https://github.com/sorayuki/obs-multi-rtmp/blob/0.2.5/src/obs-multi-rtmp.cpp#L1163

@COOLIGUAY in ur case. I think the value of `DockLocation` is a wrong number. just remove it in obs config file `%APPDATA%\obs-studio\global.ini`. the dock will be reset to left after restarting obs

so do not drag the dock to a tab or a window. the tab position or the window size cannot be saved and may cause bugs

**Comment by ace-kun-dev** [comment]
is there a fix already or any way to fix it? thanks

**Comment by sorayuki** [comment]
fixed
